<a href="https://colab.research.google.com/github/AjayNandoriya/3DMM_edges/blob/master/Reinforcement_Learning_An_Introduction_by_RSutton/Code/Example_3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

S = np.arange(25).reshape((5,5))
A = dict({'north':0, 'south':1, 'east':2, 'west':3})
R = np.zeros((4, 5,5))
R[ A['north'], :,:] = np.array([[-1,10,-1,5,-1],
                               [0,0,0,0,0],
                               [0,0,0,0,0],
                               [0,0,0,0,0],
                               [0,0,0,0,0]])
R[A['south'],:,:] = np.array([[0,10,0,5,0],
                               [0,0,0,0,0],
                               [0,0,0,0,0],
                               [0,0,0,0,0],
                               [-1,-1,-1,-1,-1]])
R[A['east'],:,:] = np.array([[0,10,0,5,-1],
                               [0,0,0,0,-1],
                               [0,0,0,0,-1],
                               [0,0,0,0,-1],
                               [0,0,0,0,-1]])
R[A['west'], :,:] = np.array([ [-1,10,0,5,0],
                               [-1,0,0,0,0],
                               [-1,0,0,0,0],
                               [-1,0,0,0,0],
                               [-1,0,0,0,0]])

S_new = np.zeros((4, 5, 5))

S_new[A['north'], :,:] = S-5
S_new[A['north'],0,:] = S[0,:]
S_new[A['north'],0,1] = 21
S_new[A['north'],0,3] = 23

S_new[A['south'],:,:] = S+5
S_new[A['south'],4,:] = S[4,:]
S_new[A['south'],0,1] = 21
S_new[A['south'],0,3] = 23

S_new[A['east'],:,:] = S+1
S_new[A['east'],:] = S[:,4]
S_new[A['east'],0,1] = 21
S_new[A['east'],0,3] = 23

S_new[A['west'],:,:] = S-1
S_new[A['west']:,0] = S[:, 0]
S_new[A['west'],0,1] = 21
S_new[A['west'],0,3] = 23

gamma = 0.9

In [12]:
print(S)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
print(S_new)

[[[ 0. 21.  2. 23.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[ 5. 21.  7. 23.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [20. 21. 22. 23. 24.]]

 [[ 4. 21. 14. 23. 24.]
  [ 4.  9. 14. 19. 24.]
  [ 4.  9. 14. 19. 24.]
  [ 4.  9. 14. 19. 24.]
  [ 4.  9. 14. 19. 24.]]

 [[ 0. 21. 10. 23. 20.]
  [ 4.  5.  6.  7.  8.]
  [ 9. 10. 11. 12. 13.]
  [14. 15. 16. 17. 18.]
  [19. 20. 21. 22. 23.]]]


In [11]:
print(R)

[[[-1. 10. -1.  5. -1.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0. 10.  0.  5.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [-1. -1. -1. -1. -1.]]

 [[ 0. 10.  0.  5. -1.]
  [ 0.  0.  0.  0. -1.]
  [ 0.  0.  0.  0. -1.]
  [ 0.  0.  0.  0. -1.]
  [ 0.  0.  0.  0. -1.]]

 [[-1. 10.  0.  5.  0.]
  [-1.  0.  0.  0.  0.]
  [-1.  0.  0.  0.  0.]
  [-1.  0.  0.  0.  0.]
  [-1.  0.  0.  0.  0.]]]
